# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainInterface.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(303, 440)
        self.tabWidget = QtWidgets.QTabWidget(TabWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 311, 451))
        self.tabWidget.setObjectName("tabWidget")
        self.Photo = QtWidgets.QWidget()
        self.Photo.setObjectName("Photo")
        self.groupBox_5 = QtWidgets.QGroupBox(self.Photo)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 120, 263, 141))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Edit_filename2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.Edit_filename2.setObjectName("Edit_filename2")
        self.gridLayout_3.addWidget(self.Edit_filename2, 0, 0, 1, 1)
        self.Button_filename2 = QtWidgets.QPushButton(self.groupBox_5)
        self.Button_filename2.setObjectName("Button_filename2")
        self.gridLayout_3.addWidget(self.Button_filename2, 0, 1, 1, 1)
        self.Label_savepath2 = QtWidgets.QLabel(self.groupBox_5)
        self.Label_savepath2.setText("")
        self.Label_savepath2.setObjectName("Label_savepath2")
        self.gridLayout_3.addWidget(self.Label_savepath2, 1, 0, 1, 1)
        self.Button_savepath2 = QtWidgets.QPushButton(self.groupBox_5)
        self.Button_savepath2.setObjectName("Button_savepath2")
        self.gridLayout_3.addWidget(self.Button_savepath2, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.Photo)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 270, 281, 111))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.Button_recording2 = QtWidgets.QPushButton(self.groupBox_3)
        self.Button_recording2.setGeometry(QtCore.QRect(20, 20, 115, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_recording2.sizePolicy().hasHeightForWidth())
        self.Button_recording2.setSizePolicy(sizePolicy)
        self.Button_recording2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./resource/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_recording2.setIcon(icon)
        self.Button_recording2.setObjectName("Button_recording2")
        self.Button_endrecording2 = QtWidgets.QPushButton(self.groupBox_3)
        self.Button_endrecording2.setGeometry(QtCore.QRect(150, 20, 115, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_endrecording2.sizePolicy().hasHeightForWidth())
        self.Button_endrecording2.setSizePolicy(sizePolicy)
        self.Button_endrecording2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./resource/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_endrecording2.setIcon(icon1)
        self.Button_endrecording2.setObjectName("Button_endrecording2")
        self.Label_mrecordingtime2 = QtWidgets.QLabel(self.groupBox_3)
        self.Label_mrecordingtime2.setGeometry(QtCore.QRect(50, 70, 151, 31))
        self.Label_mrecordingtime2.setText("")
        self.Label_mrecordingtime2.setObjectName("Label_mrecordingtime2")
        self.Button_camera2 = QtWidgets.QPushButton(self.Photo)
        self.Button_camera2.setGeometry(QtCore.QRect(20, 30, 251, 61))
        self.Button_camera2.setObjectName("Button_camera2")
        self.tabWidget.addTab(self.Photo, "")
        self.Video = QtWidgets.QWidget()
        self.Video.setObjectName("Video")
        self.Button_camera = QtWidgets.QPushButton(self.Video)
        self.Button_camera.setGeometry(QtCore.QRect(20, 30, 251, 61))
        self.Button_camera.setObjectName("Button_camera")
        self.groupBox = QtWidgets.QGroupBox(self.Video)
        self.groupBox.setGeometry(QtCore.QRect(20, 120, 263, 141))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.Edit_filename = QtWidgets.QLineEdit(self.groupBox)
        self.Edit_filename.setObjectName("Edit_filename")
        self.gridLayout.addWidget(self.Edit_filename, 0, 0, 1, 1)
        self.Button_filename = QtWidgets.QPushButton(self.groupBox)
        self.Button_filename.setObjectName("Button_filename")
        self.gridLayout.addWidget(self.Button_filename, 0, 1, 1, 1)
        self.Label_savepath = QtWidgets.QLabel(self.groupBox)
        self.Label_savepath.setText("")
        self.Label_savepath.setObjectName("Label_savepath")
        self.gridLayout.addWidget(self.Label_savepath, 1, 0, 1, 1)
        self.Button_savepath = QtWidgets.QPushButton(self.groupBox)
        self.Button_savepath.setObjectName("Button_savepath")
        self.gridLayout.addWidget(self.Button_savepath, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Video)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 270, 281, 111))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.Button_recording = QtWidgets.QPushButton(self.groupBox_2)
        self.Button_recording.setGeometry(QtCore.QRect(20, 20, 115, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_recording.sizePolicy().hasHeightForWidth())
        self.Button_recording.setSizePolicy(sizePolicy)
        self.Button_recording.setText("")
        self.Button_recording.setIcon(icon)
        self.Button_recording.setObjectName("Button_recording")
        self.Button_endrecording = QtWidgets.QPushButton(self.groupBox_2)
        self.Button_endrecording.setGeometry(QtCore.QRect(150, 20, 115, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_endrecording.sizePolicy().hasHeightForWidth())
        self.Button_endrecording.setSizePolicy(sizePolicy)
        self.Button_endrecording.setText("")
        self.Button_endrecording.setIcon(icon1)
        self.Button_endrecording.setObjectName("Button_endrecording")
        self.Label_mrecordingtime = QtWidgets.QLabel(self.groupBox_2)
        self.Label_mrecordingtime.setGeometry(QtCore.QRect(50, 70, 151, 31))
        self.Label_mrecordingtime.setText("")
        self.Label_mrecordingtime.setObjectName("Label_mrecordingtime")
        self.tabWidget.addTab(self.Video, "")
        self.Live = QtWidgets.QWidget()
        self.Live.setObjectName("Live")
        self.label_8 = QtWidgets.QLabel(self.Live)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 291, 31))
        self.label_8.setObjectName("label_8")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.Live)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 30, 301, 381))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_4.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_4.addTab(self.tab_4, "")
        self.tabWidget.addTab(self.Live, "")
        self.View = QtWidgets.QWidget()
        self.View.setObjectName("View")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.View)
        self.tabWidget_2.setGeometry(QtCore.QRect(-8, -1, 311, 411))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.videoview = QtWidgets.QWidget()
        self.videoview.setObjectName("videoview")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.videoview)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 311, 381))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 20, 271, 111))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Label_videopath = QtWidgets.QLabel(self.groupBox_4)
        self.Label_videopath.setText("")
        self.Label_videopath.setObjectName("Label_videopath")
        self.gridLayout_2.addWidget(self.Label_videopath, 0, 0, 1, 1)
        self.Button_videopath = QtWidgets.QPushButton(self.groupBox_4)
        self.Button_videopath.setObjectName("Button_videopath")
        self.gridLayout_2.addWidget(self.Button_videopath, 1, 0, 1, 1)
        self.Button_videoview = QtWidgets.QPushButton(self.tab_5)
        self.Button_videoview.setGeometry(QtCore.QRect(10, 180, 251, 71))
        self.Button_videoview.setObjectName("Button_videoview")
        self.tabWidget_3.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_6.setGeometry(QtCore.QRect(30, 40, 251, 111))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Label_photopath = QtWidgets.QLabel(self.groupBox_6)
        self.Label_photopath.setText("")
        self.Label_photopath.setObjectName("Label_photopath")
        self.verticalLayout_2.addWidget(self.Label_photopath)
        self.Button_photopath = QtWidgets.QPushButton(self.groupBox_6)
        self.Button_photopath.setObjectName("Button_photopath")
        self.verticalLayout_2.addWidget(self.Button_photopath)
        self.Button_photoview = QtWidgets.QPushButton(self.tab_6)
        self.Button_photoview.setGeometry(QtCore.QRect(30, 210, 251, 71))
        self.Button_photoview.setObjectName("Button_photoview")
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tabWidget_2.addTab(self.videoview, "")
        self.photoview = QtWidgets.QWidget()
        self.photoview.setObjectName("photoview")
        self.tabWidget_2.addTab(self.photoview, "")
        self.tabWidget.addTab(self.View, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 291, 391))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 57 italic 24pt \"Ubuntu\";\n"
"background-color: rgb(0, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.username = QtWidgets.QLineEdit(self.layoutWidget)
        self.username.setDragEnabled(False)
        self.username.setObjectName("username")
        self.horizontalLayout_3.addWidget(self.username)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.password = QtWidgets.QLineEdit(self.layoutWidget)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.horizontalLayout_2.addWidget(self.password)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 9)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.checkpsw = QtWidgets.QLineEdit(self.layoutWidget)
        self.checkpsw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.checkpsw.setObjectName("checkpsw")
        self.horizontalLayout.addWidget(self.checkpsw)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 9)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnLogin = QtWidgets.QPushButton(self.layoutWidget)
        self.btnLogin.setObjectName("btnLogin")
        self.horizontalLayout_4.addWidget(self.btnLogin)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.btnLoginreset = QtWidgets.QPushButton(self.layoutWidget)
        self.btnLoginreset.setObjectName("btnLoginreset")
        self.horizontalLayout_4.addWidget(self.btnLoginreset)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 291, 391))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 57 italic 24pt \"Ubuntu\";\n"
"background-color: rgb(0, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.newname = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.newname.setDragEnabled(False)
        self.newname.setObjectName("newname")
        self.horizontalLayout_5.addWidget(self.newname)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.newpasswd = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.newpasswd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newpasswd.setObjectName("newpasswd")
        self.horizontalLayout_6.addWidget(self.newpasswd)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.checknewpasswd = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.checknewpasswd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.checknewpasswd.setObjectName("checknewpasswd")
        self.horizontalLayout_9.addWidget(self.checknewpasswd)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btnSignin = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btnSignin.setObjectName("btnSignin")
        self.horizontalLayout_8.addWidget(self.btnSignin)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.btnSignreset = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btnSignreset.setObjectName("btnSignreset")
        self.horizontalLayout_8.addWidget(self.btnSignreset)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 2)
        self.horizontalLayout_8.setStretch(2, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(TabWidget)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "Form"))
        self.groupBox_5.setTitle(_translate("TabWidget", "File name and File path"))
        self.Button_filename2.setText(_translate("TabWidget", "文件名"))
        self.Button_savepath2.setText(_translate("TabWidget", "文件路径"))
        self.Button_camera2.setText(_translate("TabWidget", "开始拍照"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Photo), _translate("TabWidget", "拍照"))
        self.Button_camera.setText(_translate("TabWidget", "启动摄像头"))
        self.groupBox.setTitle(_translate("TabWidget", "File name and File path"))
        self.Button_filename.setText(_translate("TabWidget", "文件名"))
        self.Button_savepath.setText(_translate("TabWidget", "文件路径"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Video), _translate("TabWidget", "短视频"))
        self.label_8.setText(_translate("TabWidget", "提示:仅支持一人直播多人收听模式"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_3), _translate("TabWidget", "我要直播"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_4), _translate("TabWidget", "我看直播"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Live), _translate("TabWidget", "直播"))
        self.Button_videopath.setText(_translate("TabWidget", "视频路径"))
        self.Button_videoview.setText(_translate("TabWidget", "点击播放"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("TabWidget", "视频"))
        self.Button_photopath.setText(_translate("TabWidget", "照片路径"))
        self.Button_photoview.setText(_translate("TabWidget", "点击查看"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("TabWidget", "照片"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.videoview), _translate("TabWidget", "本地文件"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.photoview), _translate("TabWidget", "我的云端"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.View), _translate("TabWidget", "查看"))
        self.label_4.setText(_translate("TabWidget", "我要登录"))
        self.label.setText(_translate("TabWidget", "账号:"))
        self.username.setPlaceholderText(_translate("TabWidget", "请输入账号"))
        self.label_2.setText(_translate("TabWidget", "密码:"))
        self.password.setPlaceholderText(_translate("TabWidget", "请输入密码"))
        self.label_5.setText(_translate("TabWidget", "再次输入密码:"))
        self.checkpsw.setPlaceholderText(_translate("TabWidget", "请再次输入密码"))
        self.btnLogin.setText(_translate("TabWidget", "登录"))
        self.btnLoginreset.setText(_translate("TabWidget", "重置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TabWidget", "登录"))
        self.label_6.setText(_translate("TabWidget", "我要注册"))
        self.label_3.setText(_translate("TabWidget", "账号:"))
        self.newname.setPlaceholderText(_translate("TabWidget", "请输入您的新账号"))
        self.label_7.setText(_translate("TabWidget", "密码:"))
        self.newpasswd.setPlaceholderText(_translate("TabWidget", "请输入您的密码"))
        self.label_9.setText(_translate("TabWidget", "重复密码:"))
        self.checknewpasswd.setPlaceholderText(_translate("TabWidget", "请再次输入您的密码"))
        self.btnSignin.setText(_translate("TabWidget", "注册"))
        self.btnSignreset.setText(_translate("TabWidget", "重置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("TabWidget", "注册"))

